/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as PartnershipRouteImport } from './routes/partnership'
import { Route as RecruitmentRouteImport } from './routes/recruitment'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as TechnicalExpertiseRouteImport } from './routes/technical-expertise'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as ApiZohoCallbackRouteImport } from './routes/api/zoho/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipRoute = PartnershipRouteImport.update({
  id: '/partnership',
  path: '/partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitmentRoute = RecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalExpertiseRoute = TechnicalExpertiseRouteImport.update({
  id: '/technical-expertise',
  path: '/technical-expertise',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZohoCallbackRoute = ApiZohoCallbackRouteImport.update({
  id: '/api/zoho/callback',
  path: '/api/zoho/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessments': typeof AssessmentsRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/partnership': typeof PartnershipRoute
  '/recruitment': typeof RecruitmentRoute
  '/solutions': typeof SolutionsRoute
  '/technical-expertise': typeof TechnicalExpertiseRoute
  '/training': typeof TrainingRoute
  '/api/zoho/callback': typeof ApiZohoCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessments': typeof AssessmentsRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/partnership': typeof PartnershipRoute
  '/recruitment': typeof RecruitmentRoute
  '/solutions': typeof SolutionsRoute
  '/technical-expertise': typeof TechnicalExpertiseRoute
  '/training': typeof TrainingRoute
  '/api/zoho/callback': typeof ApiZohoCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessments': typeof AssessmentsRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/partnership': typeof PartnershipRoute
  '/recruitment': typeof RecruitmentRoute
  '/solutions': typeof SolutionsRoute
  '/technical-expertise': typeof TechnicalExpertiseRoute
  '/training': typeof TrainingRoute
  '/api/zoho/callback': typeof ApiZohoCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assessments'
    | '/contact'
    | '/industries'
    | '/partnership'
    | '/recruitment'
    | '/solutions'
    | '/technical-expertise'
    | '/training'
    | '/api/zoho/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assessments'
    | '/contact'
    | '/industries'
    | '/partnership'
    | '/recruitment'
    | '/solutions'
    | '/technical-expertise'
    | '/training'
    | '/api/zoho/callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assessments'
    | '/contact'
    | '/industries'
    | '/partnership'
    | '/recruitment'
    | '/solutions'
    | '/technical-expertise'
    | '/training'
    | '/api/zoho/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssessmentsRoute: typeof AssessmentsRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  PartnershipRoute: typeof PartnershipRoute
  RecruitmentRoute: typeof RecruitmentRoute
  SolutionsRoute: typeof SolutionsRoute
  TechnicalExpertiseRoute: typeof TechnicalExpertiseRoute
  TrainingRoute: typeof TrainingRoute
  ApiZohoCallbackRoute: typeof ApiZohoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnership': {
      id: '/partnership'
      path: '/partnership'
      fullPath: '/partnership'
      preLoaderRoute: typeof PartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruitment': {
      id: '/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof RecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-expertise': {
      id: '/technical-expertise'
      path: '/technical-expertise'
      fullPath: '/technical-expertise'
      preLoaderRoute: typeof TechnicalExpertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zoho/callback': {
      id: '/api/zoho/callback'
      path: '/api/zoho/callback'
      fullPath: '/api/zoho/callback'
      preLoaderRoute: typeof ApiZohoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssessmentsRoute: AssessmentsRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  PartnershipRoute: PartnershipRoute,
  RecruitmentRoute: RecruitmentRoute,
  SolutionsRoute: SolutionsRoute,
  TechnicalExpertiseRoute: TechnicalExpertiseRoute,
  TrainingRoute: TrainingRoute,
  ApiZohoCallbackRoute: ApiZohoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
